### ISSUE TITLE
Problemas con el offset

### ISSUE THREAD

**Issue by APoloG13** [elgambitero/Slic3r-settings#1]
Muy buenas,

Estoy utilizando tu código para slic3r (concretamente el Hephestos 2, con el código HD y con el del filamento Grey) y lo que me ocurre es que cada vez que acaba una impresión y tengo que realizar otra, tengo que volver a calibrar el offset unos 0,1 - 0,2 mm porque si no no imprime al estar en contacto directo con la base.

Es el único "fallo" que me ha dado ese código, por todo lo demas, las impresiones son espectaculares, nivel de detalle increible, no quedan las cuerdas colgando entre modelos, quedan completamente lisos no hace falta ni lijar... Solo ese pequeño "fallo".

Alguna idea de como arreglarlo o sabes porque pasa esto?

Muchas gracias por tu trabajo, espero que sigas completandolo con los nuevos tipos de filamento (me encantaria ver lo que puede pasar con los especiales de filaflex, madera, cobre y bronce si consigues el mismo nivel que con el PLA)

**Comment by gvJaime** [comment]
Buenas @APoloG13

Me alegro muchísimo de que uses mis settings! Me gusta hacer las piezas con cuidao y cariño.

Muchas gracias por la review!

Ahora bien, conozco el problema. Ocurre en Hephestos 2 y ocurría cuando tenía acceso a Witbox 2. La autonivelación símplemente no se porta bien con slic3r, y aún no he llegado a entender por qué ocurre.

Unas dudillas: cuando me dices que tienes que calibrar el offset entre impresión e impresión, quieres decir que con cada impresión que haces, el extrusor queda cada vez mas bajo? Que ocurre si en vez de nivelar cada vez, lo dejas a su aire? Se va hincando más el extrusor?

Mi experiencia de los ultimos 3 meses con hephestos 2:
La máquina empieza, tras nivelar, y deja el filamento muy aplastado en la derecha de la bandeja, y muy lejos en la izda. Solía calibrar tocando los knobs de la bandeja conforme empezaba a imprimir, hasta que todo se convertía en un desastre, y tenía que recalibrar (para volver a las andadas, de tener que recalibrar con los knobs)

Con witbox: 
Las impresiones se me quedaban muy pegadas. Incluso con la 1. Cosa que por lo visto con Cura no ocurre.
Analizando los Gcodes de Cura y Slic3r para la misma pieza y settings similares (cogí el standard de 0.24mm) puedo comprobar que ambos empiezan a la misma altura. De hecho, en Slic3r dejo la primera capa siempre de 0.24mm, para paliar problemas de nivelación, se me sigue escapando algo.

Tengo mis teorías:
- Existe un start.gcode al principio de todos los gcodes. Si no recuerdo mal, éste tenía ordenes de dejar el nozzle un pelín por encima de la base. Me pregunto si en algún descuido habré reseteado incorrectamente las coordenadas, o habré mandado un parámetro que confunda a la máquina. (Lo revisaré)
- Inconsistencias en la posición del eje vertical. Me pregunto si es posible que al levantar el nozzle, éste no se quede todo lo levantado que debería, y luego baje demasiado. Es posible que la rutina de Cura haga que estos fenómenos aparezcan menos. Las aceleraciones bajas podrían estar jugando un papel en esto. (Esto no podré revisarlo hasta que vuelva de vacaciones)

Propongo un par de cosas (mas bien, las anoto aquí):
- revisar los comandos al principio de un gcode hecho por slic3r, tomando nota de las coordenadas para ver si ocurre algún desajuste
- copiar el start.gcode de cura en Slic3r, y hacer una impresión para ver si se queda igual de mal nivelado.

**Comment by APoloG13** [comment]
Jaime yo tengo la auto nivelación de hephestos 2 quitada, y lo que hace es
cuando acaba cada impresión el inicio está en una posición inferior a la
anterior por lo que calibró el extrusor para ajustarlo a una buena salida.
En cuanto a lo de que tienes un lado más pegado que el otro, fíjate que no
tengas el puente donde va el extrusor un lado un poco más levantado que el
otro.

Te puedo asegurar que la velocidad y la cantidad de pla extruido es la
correcta, no obstante yo retocaría lo de la temperatura: 210 las dos o tres
primeras capas para que se asiente bien y se adhiera y luego las demás a
206 o similar. Yo cambié esos parámetros y créeme que los resultados son
más que satisfactorios (imprimí piezas para hacer un palo de gopro que se
dobla con tuercas y es un gustazo el no tener que lijar aunque sí tuve que
dar unas pasadas entre las mismas piezas para que el movimiento fuera
fluido, pero el cuerpo del objeto era completamente liso)

Yo solo llevo dos meses desde que me regalaron la impresora, y con tus
settings ha sido un gran avance y una satisfacción increíble porque es eso,
te deja acabados profesionales y es fácil de usar.

En cuanto cura/slic3r, la verdad es que cura te lo pone todo más sencillo
pero slic3r es más perfeccionista al poder tocar bastante más parámetros.
Quizás sea eso, solo un problema del código que se pasó algo o un error
minúsculo.

Espero que sigas actualizando y sacando settings (creo que después del PLA,
tu mayor reto serán los filamentos especiales: filaflex, cobre, bronce y
madera). Pero estoy seguro que una vez encontrado ese error, todo saldrá
perfecto.

**Comment by gvJaime** [comment]
Tras unos mesecillos de esparcimiento he vuelto a usar la impresión 3D activamente.

Es posible que el puente del extrusor de la Hephestos 2 esté un poco torcidillo, además de la placa del sensor capacitivo.
En cuanto tenga un poco de tiempo, comprobaré lo que propuse en la respuesta anterior. (mirar los start.gcode por si acaso) También miraré lo de la temperatura del filamento a 206ºC. Últimamente he tenido acabados feos con el PLA negro, y a lo mejor extruyéndolo a menos temperatura se queda mejor.

@APoloG13 , con la autonivelación desactivada, ¿sigues teniendo una parte más despegada que otra en la base? A mí me pasaba con la autonivelación (la esquina del fondo izquierda se quedaba casi en el aire).  He desactivado la autonivelación esta semana, y parece que va bien, pero sólamente lo he probado una vez.

**Comment by APoloG13** [comment]
A día de hoy he cambiado de software, actualmente uso simplify3D y la
verdad es que es todo más simple, no está tan optimizado como los tuyos
pero ahí vamos. En cuanto a problemas con el nivelado por ahora 0

**Comment by gvJaime** [comment]
Durante estos ultimos 6 meses he podido analizar más la máquina, y he podido concluir que el problema consiste en una torsión en las varillas del eje Y, tal que éstas no están contenidas en el mismo plano.

Esto se traduce en que cuando la plataforma se mueve, la bandeja gira, de manera que la línea que recorre el nozzle a lo largo del eje X ya no está paralela a la bandeja. Por eso es imposible nivelar la plataforma.

Este tipo de problemas son esperables, ya que la Hephestos 2 tiene unas varillas de nada mas y nada menos que 300mm y pico, que se doblan con mirarlas. Cabe pensar perfectamente que con el uso vayan deformándose.

Como es un problema de mecánica, y @APoloG13 ya no usa este software, cierro este issue.

**Comment by APoloG13** [comment]
No hay ninguna solución para evitar que se doblen? Algo como una unión que
permita que se deslice la plataforma pero dándole más rigidez a las
natillas a la vez?

Algo tipo túnel se me ocurre, este finde investigaré un poco la impresora a
fondo y si quieres Jaime, hablamos y miramos a ver si podemos encontrar una
solución. La hephestos 2 hay que reconocer que es una impresora con mucho
potencial pero está diseñada como con prisa.
